Feature/1207515694088907 sdk update
peaqnetwork/peaq-js pull request #11
Opened 2024-06-07 19:13 UTC by jpgundrum

sdk update to have expected behavior.
- Add update/remove to peaqDid
- Create a storage function to add, read, update, and remove objects to the peaq storage pallet
- Revise test cases
- Update interfaces that broke fetches

2024-06-07 19:15 UTC, jpgundrum commented on packages/sdk/src/modules/storage/index.ts
> +export class Storage extends Base {
new storage function

2024-06-07 19:15 UTC, jpgundrum commented on packages/sdk/src/modules/storage/storage.spec.ts
> +describe('Storage', () => {
basic storage tests

2024-06-07 19:15 UTC, jpgundrum commented on packages/sdk/src/modules/base/index.ts
>  type TErrorData = {
Object not built correctly. Have to have dispatchError and dispatchInfo fields

2024-06-07 19:16 UTC, jpgundrum commented on packages/sdk/src/modules/base/index.ts
>    protected async _transactionError(
Never called _transactionError in previous base/index.ts file. Now it gets called if a failed extrinsic event is found.

2024-06-07 19:16 UTC, jpgundrum commented on packages/sdk/src/modules/base/index.ts
> +      const moduleIdx = errorData?.dispatchError?.Module?.index;
extracts error information from the object returned from the PeaqEventData

2024-06-07 19:18 UTC, jpgundrum commented on packages/sdk/src/modules/base/index.ts
> +                    const events = await result.events; // get events
Above line did not properly get the event data for extrinsics. Now using result.events to get the events to create a mapping and filter to check for an "ExtrinsicFailed" event. If one is found, _transactionError gets called to build the failure message, and an Error is thrown.

2024-06-07 19:19 UTC, jpgundrum commented on packages/sdk/src/modules/did/did.spec.ts
> +      await createReadRemove(new_did, did, alice, null);
updated tests to use functions to test for proper did creation. It creats a did, reads it, and then removes it.

2024-06-07 19:20 UTC, jpgundrum commented on packages/sdk/src/modules/did/did.spec.ts
> +      const peaqServiceProto = new peaqDidProto.Service();
using peaqProto to build the customDocumentFields. Change customDocumentFields in the did/index.ts to be expecting these types.

2024-06-07 19:21 UTC, jpgundrum commented on packages/sdk/src/modules/did/did.spec.ts
> +async function createReadRemove(new_did: string, did: Did, alice: KeyringPair, customFields: CustomDocumentFields | null) {
executes verbose testing on the functions that call the method

2024-06-07 19:23 UTC, jpgundrum commented on packages/sdk/src/modules/did/did.spec.ts
> +          // expect(verification.publicKeyMultibase).toEqual(`z${alice.address}`);
Currently having an issue where the proto document is not built correctly to test this line. You can see [here](https://github.com/peaqnetwork/peaq-network-did-proto-format/blob/feature/1206361464402337_develop-data-verification-flutter-peaq-sdk-package/javascript/did_document_format_pb.js) that the publickeymulibase does not use camelCase. The update [branch](https://github.com/peaqnetwork/peaq-network-did-proto-format/blob/feature/1207515694088897_proto_name_fix/javascript/did_document_format_pb.js) fixes this issue.

2024-06-07 19:24 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +  signatures?: peaqDidProto.Signature[],
CustomDocumentFields are now defined by the peaqDidProto document.

2024-06-07 19:26 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +  public async update(options: UpdateDidOptions,
Added function to update an already present did. How should the update occur? Should it overwrite the previous document by creating a new did document, or only update what is specified?

2024-06-07 19:26 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +  public async remove(options: RemoveDidOptions,
Added a remove function to remove the did at the given name

2024-06-07 19:26 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +  private _createSignature(signature: peaqDidProto.Signature) {
Added a signature method to add a signature to the did document

2024-06-07 19:27 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +    if (options.customDocumentFields?.verifications) {
Added loop for verifications, in case the user is trying to set multiple verification methods at the same time.

2024-06-07 19:29 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/index.ts
> +      const responseData: ResponseFetchGroup[] = groups?.map((item) =>
Fixes the object issue we were having before where using {} when calling the function did not work. Changed the parameter to be an object so this syntax can work, as that is how all our other functions are called.

2024-06-07 19:29 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/rbac.spec.ts
> +  }, 40000);
TODO: update RBAC tests

2024-06-14 17:48 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/index.ts
> +interface DeleteRole {
new delete objects to be passed

2024-06-14 17:49 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/index.ts
> +  public async deleteRole(options: DeleteRole): Promise<{log: string;}> {
delete role, group, and permission added

2024-06-14 17:49 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/index.ts
> +        'unassignRoleToGroup'
fixed bug for improper pallet call

2024-06-14 17:50 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/rbac.spec.ts
> +describe.skip('RBAC', () => {
added new rbac tests

2024-06-14 17:50 UTC, jpgundrum commented on packages/sdk/src/modules/rbac/rbac.spec.ts
> +// old tests
old tests that were previously used

2024-06-19 21:43 UTC, jpgundrum commented on packages/sdk/src/modules/base/index.ts
> -                    const eventsTriggeredByTx: any = []
previous event log did not work. Updated to fix and now resolves to peaqEvents with data

2024-06-19 21:44 UTC, jpgundrum commented on packages/sdk/src/modules/base/index.ts
> -                    const eventsTriggeredByTx: any = []
previous event log did not work. Updated to fix and now resolves to peaqEvents with data

2024-06-19 21:45 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +      const eventData = await this._newSignTx({ nonce, address: keyPair, extrinsics: attributeExtrinsic });
use the returned object to get the block hash and return to the caller

2024-06-20 19:25 UTC, jpgundrum commented on packages/sdk/src/modules/did/index.ts
> +      const did_document = await this.read({name, address});
Should a check be added to make sure that the read controller of the DID is the same address as the one that calls the update method? The controller should be the only person that can update the DID Document.

2024-06-26 10:20 UTC, irediaes requested changes
Great attempts on your first PR.
But I tried reviewing this and I discovered there were too many changes.
It is difficult to do a good review. I checked your commits and they were also not consistence.
Please separate each new feature into a different task/feature branch and create a new PR to this effect.
For example: If your are adding a new feature like "Add Storage Item"; a new task and feature branch should be created for this and new PR should be created when you are done. And when you make any relevant changes on the branch, you should create a new commit.
I would have ignore this but the repo your are working is already public. The commit messages have to be organized and descriptive; for the sdk consumers and future collaborators.
Please read more here on our Git standards:
https://eotlabs.slab.com/posts/git-standards-8bighc18

2024-06-26 10:20 UTC, irediaes commented on packages/sdk/src/modules/did/index.ts
> +}
Why is `Verification` only having the field `type`?

2024-06-26 10:20 UTC, irediaes commented on packages/sdk/src/modules/did/index.ts
> +      throw new Error(`Create DID ${error}`); // slight error prose improvement -> TODO create custom errors
This should be reverted to the previous description.
It more readable. `Error creating DID: ${error}`

2024-06-26 10:20 UTC, irediaes commented on packages/sdk/src/modules/did/index.ts
> +      const did_document = await this.read({name, address});
Please make the update DID a different PR.
It will be easier to review.

2024-06-29 08:40 UTC, closed without merging