feat: peaq storage
peaqnetwork/peaq-js pull request #17
Opened 2024-07-01 16:42 UTC by jpgundrum

Added capability for user to interact with our storage pallet using the sdk.

**WIP**: 
- Need to have discussions about best practices and logic for the implementation
- Add more function testing

2024-08-30 21:05 UTC, jpgundrum commented on packages/sdk/src/modules/storage/index.ts
> +type AddItemOptions = {
currently have it so only a string can be set for itemType and item. Should this be changed to offer more types?

2024-08-30 21:05 UTC, jpgundrum commented on packages/sdk/src/modules/storage/index.ts
> +        if (stringToU8a(itemType).length > 64) throw new ItemTypeError('New Item Type cannot be larger than 64 bytes');
performs an error check for itemType and item size to reduce the amount of extrinsics sent to the peaq node

2024-09-16 08:57 UTC, irediaes requested changes

2024-09-16 08:57 UTC, irediaes commented on packages/sdk/src/modules/storage/index.ts
> +            };
Please return the item just as it was stored on chain.
Don't parse it using `toHuman`.

2024-09-16 08:57 UTC, irediaes commented on packages/sdk/src/modules/storage/index.ts
> +    log: string;
Why naming it "log"?

"message" should fit better

2024-09-16 08:57 UTC, irediaes commented on packages/sdk/src/modules/storage/index.ts
> +    log: string;
"message" fit better.

2024-09-16 08:57 UTC, irediaes commented on packages/sdk/src/modules/storage/index.ts
> +    log: string;
"message" fit better.

2024-09-16 08:57 UTC, irediaes commented on packages/sdk/src/modules/storage/index.ts
> +    log: string;
"data" fit better.

2024-09-18 17:15 UTC, merged