Fix/1208238364944975 offline initialization
peaqnetwork/peaq-js pull request #29
Opened 2024-09-05 18:00 UTC by jpgundrum

When creating an offline instance, empty values for api and constructor in DID/RBAC are set to avoid warnings that are issued when the function await Sdk.createOfflineInstance(); is used in practice

2024-09-05 18:01 UTC, jpgundrum commented on packages/sdk/src/modules/main/index.ts
>    constructor(options: Options) {
@irediaes Please see the constructor here.

2024-09-06 10:00 UTC, irediaes requested changes
Too many messy hacks.

Please try this instead:

```
constructor(options: Options) {
   super();
    this._options = options;
    this._api = this._createApi(options);
    this._metadata = {};
    
    this.did = new Did(this._api, this._metadata);
    this.rbac = new RBAC(this._api, this._metadata);
}
```
Then createInstance():

```
 public static async createInstance(options: Options): Promise<Main> {
    await cryptoWaitReady();
    const sdk = new Main(options);
    await sdk.connect();
    return sdk;
  }
```

Change `createOfflineInstance` to `generateDidDocument` in the Main class:
Other irrelevant did methods won't be exposed if implemented this way.

```

public static async generateDidDocument(options: GenerateDidOptions): Promise<GenerateDidResult> {
      const did = new Did();
      return did.generateDidDocument(options);
}
```

so usage will be:

```
import {Sdk} from `@peaq-network/sdk

const didVal = await Sdk.generateDidDocument({name:"DID"});

```

Let me know what you think.

2024-09-06 10:00 UTC, irediaes commented on packages/sdk/src/modules/main/index.ts
> +  protected override _api: ApiPromise | undefined;
revert back to previous.
remove "undefined"

2024-09-06 10:00 UTC, irediaes commented on packages/sdk/src/modules/main/index.ts
> +  static offlineMode: boolean;
remove please.
Check my suggested implementation below

2024-09-06 10:00 UTC, irediaes commented on packages/sdk/src/modules/main/index.ts
> +    }
Too many messy hacks.

Please try this instead:

```
constructor(options: Options) {
   super();
    this._options = options;
    this._api = this._createApi(options);
    this._metadata = {};
    
    this.did = new Did(this._api, this._metadata);
    this.rbac = new RBAC(this._api, this._metadata);
}
```
Then createInstance():

```
 public static async createInstance(options: Options): Promise<Main> {
    await cryptoWaitReady();
    const sdk = new Main(options);
    await sdk.connect();
    return sdk;
  }
```

Change `createOfflineInstance` to `generateDidDocument` in the Main class:
Other irrelevant did methods won't be exposed if implemented this way.

```

public static async generateDidDocument(options: GenerateDidOptions): Promise<GenerateDidResult> {
      const did = new Did();
      return did.generateDidDocument(options);
}
```

so usage will be:

```
import {Sdk} from `@peaq-network/sdk

const didVal = await Sdk.generateDidDocument({name:"DID"});

```

2024-09-06 13:14 UTC, jpgundrum commented on packages/sdk/src/modules/main/index.ts
> +    }
This works. Thanks.

2024-09-06 14:49 UTC, jpgundrum commented
Closing this pull request to rename the branch to a more appropriate name.

2024-09-06 14:49 UTC, closed without merging